version: '3.4'

services:
  advertdb:
    image: mongo
    
  rabbitmq:
    image: rabbitmq:3-management-alpine

  arabamcomassignment:
    image: ${DOCKER_REGISTRY-}arabamcomassignment
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  mongo_data: 